# docker-host-vm/Vagrantfile

Vagrant.configure("2") do |config|
  config.vm.box = "coreos-alpha"

  # Felix
  config.vm.network "private_network", ip: "192.168.33.10"

  # Oscar
  config.vm.network "private_network", ip: "192.168.33.11"
end
